
server:
  port: 8080
  servlet:
    context-path: /secure-prints
    session:
      cookie:
        secure: true
        same-site: none
        http-only: true

spring:
  application:
    name: secure-prints
  mail:
    host: email-smtp.us-east-1.amazonaws.com
    port: 587
    #port: 25
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: true
    show-sql: false

aws:
  s3:
    bucket-name: secure-prints-s3

secure-prints:
  encryption:
    secret-key: ${ENCRYPTION_SECRET_KEY}
  appointment:
    cut-from-start-index: 0
    cut-from-end-index: 0
    start-work-hour: 10
    end-work-hour: 16
    start-break-hour: 0
    end-break-hour: 0
